"""Torch-free drawing for the on-device (Orin) demo.

The renderer must run standalone on the Orin, where neither torch nor
pycocotools exists: bevlane/demo_rgbd_bev.py imports torch at module level and
autolabel_bev imports pycocotools, so the three camera-overlay helpers are
extracted VERBATIM here (generated by scripts, not hand-edited -- keep them in
sync by regenerating) and the BEV palette is baked in as a literal.
"""
import cv2
import os
import numpy as np

# autolabel_bev is the single source of the palette. Keeping a copy here would hide
# color mismatches between local and Orin (duplicate removed 2026-08-24).
try:
    import sys as _sys, os as _os
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(
        _os.path.abspath(__file__))))
    from autolabel_bev import PALETTE          # noqa: E402
except Exception:      # autolabel_bev is not shipped on Orin
    PALETTE = np.array([[0, 0, 0], [90, 90, 90], [140, 90, 160], [0, 200, 200], [255, 255, 255], [255, 40, 40], [255, 140, 0], [240, 220, 60], [40, 60, 140]], np.uint8)

DET10_PAL = [[255, 255, 255], [0, 0, 255], [0, 160, 165], [100, 0, 200], [128, 255, 0], [255, 255, 0], [255, 0, 32], [128, 255, 0], [250, 0, 255], [0, 255, 0]]
DET10_ABBR = ["obs", "car", "trk", "bus", "bcy", "mcy", "ped", "pnt", "tl", "ts"]


_HIDE2D = {int(x) for x in os.environ.get("METEOR_2D_HIDE", "").split(",") if x.strip().isdigit()}


def draw_boxes2d(img, blist, cw, ch):
    # METEOR_2D_HIDE="7" etc. selects classes not to draw (2026-09-06: 7=road paint
    # (arrows/text); its big green boxes look like false positives, so hidden by default)
    if _HIDE2D:
        blist = [b for b in blist if int(b[0]) not in _HIDE2D]
    """Per-camera 10-class 2D boxes (cls,score,cx,cy,w,h in 768x432 px)."""
    sx, sy = cw / 768.0, ch / 432.0
    for cls, sc, cx, cy, w, h in blist:
        c = tuple(int(v) for v in DET10_PAL[int(cls)][::-1])   # RGB -> BGR
        x1, y1 = int((cx - w / 2) * sx), int((cy - h / 2) * sy)
        x2, y2 = int((cx + w / 2) * sx), int((cy + h / 2) * sy)
        cv2.rectangle(img, (x1, y1), (x2, y2), c, 2)
        tag = f"{DET10_ABBR[int(cls)]}{int(sc * 100):d}"
        (tw, th), _ = cv2.getTextSize(tag, cv2.FONT_HERSHEY_SIMPLEX, 0.38, 1)
        ty = max(y1, th + 3)
        cv2.rectangle(img, (x1, ty - th - 3), (x1 + tw + 2, ty + 1), c, -1)
        cv2.putText(img, tag, (x1 + 1, ty - 2), cv2.FONT_HERSHEY_SIMPLEX,
                    0.38, (0, 0, 0), 1, cv2.LINE_AA)

# surround order for the 2x3 grids (front row / back row)
SURR = ["CAM_FRONT_LEFT", "CAM_FRONT_WIDE", "CAM_FRONT_RIGHT",
        "CAM_BACK_LEFT", "CAM_BACK_WIDE", "CAM_BACK_RIGHT"]
NARROW = ["CAM_FRONT_NARROW", "CAM_BACK_NARROW"]

# demo palette: hide sidewalk(2) & parking(8) — they are noisy, show as black
DEMO_PALETTE = np.zeros((12, 3), np.uint8)
DEMO_PALETTE[:len(PALETTE)] = PALETTE
DEMO_PALETTE[2] = 0
DEMO_PALETTE[8] = 0
DEMO_PALETTE[10] = (255, 215, 0)    # predicted vehicle box (gold)
DEMO_PALETTE[11] = (255, 0, 255)    # predicted VRU box (magenta)

SEG2D_PAL = np.zeros((256, 3), np.uint8)
SEG2D_PAL[:11] = [(90, 90, 90),     # road
                  (255, 255, 255),  # lane/marking
                  (160, 90, 140),   # sidewalk
                  (255, 200, 0),    # crosswalk (cyan-ish BGR)
                  (0, 140, 255),    # vehicle (orange)
                  (0, 0, 230),      # person (red)
                  (60, 90, 140),    # building
                  (60, 160, 60),    # vegetation
                  (200, 130, 50),   # sky (light blue BGR)
                  (0, 230, 230),    # pole/sign (yellow)
                  (70, 70, 70)]     # freespace



BOX_EDGES = [(0, 1), (1, 2), (2, 3), (3, 0), (4, 5), (5, 6), (6, 7), (7, 4),
             (0, 4), (1, 5), (2, 6), (3, 7)]


def draw_boxes_on_rgb(img, det_boxes, K, Tce, cw, ch, W0=768, H0=432):
    """Project decoded BEV boxes (ego frame) into a camera and draw 3D
    wireframes with distance labels. Edges are CLIPPED at the camera near
    plane so nearby vehicles on side cameras are still drawn (partial box)."""
    sx, sy = cw / W0, ch / H0
    EPS = 0.25

    def proj(p):
        return (int((K[0, 0] * p[0] / p[2] + K[0, 2]) * sx),
                int((K[1, 1] * p[1] / p[2] + K[1, 2]) * sy))

    for cls, sc, xe, ye, l, w, yaw in det_boxes:
        hgt = 1.6 if cls == 0 else 1.7
        cb, sb = np.cos(yaw), np.sin(yaw)
        bot = []
        for lx, wy in ((l/2, w/2), (l/2, -w/2), (-l/2, -w/2), (-l/2, w/2)):
            bot.append([xe + lx*cb - wy*sb, ye + lx*sb + wy*cb, 0.0])
        cors = np.array(bot + [[b[0], b[1], hgt] for b in bot])
        pc = cors @ Tce[:3, :3].T + Tce[:3, 3]
        z = pc[:, 2]
        if (z > EPS).sum() == 0:          # entirely behind the camera
            continue
        col = (0, 215, 255) if cls == 0 else (255, 0, 255)
        vis_pts = []
        for a, b in BOX_EDGES:
            pa, pb = pc[a].copy(), pc[b].copy()
            za, zb = pa[2], pb[2]
            if za < EPS and zb < EPS:
                continue
            if za < EPS or zb < EPS:      # clip the edge at the near plane
                t = (EPS - za) / (zb - za)
                pclip = pa + t * (pb - pa)
                if za < EPS:
                    pa = pclip
                else:
                    pb = pclip
            A, B = proj(pa), proj(pb)
            if abs(A[0]) > cw * 8 or abs(B[0]) > cw * 8                     or abs(A[1]) > ch * 8 or abs(B[1]) > ch * 8:
                continue
            cv2.line(img, A, B, col, 1, cv2.LINE_AA)
            vis_pts += [A, B]
        if vis_pts:
            us = [p[0] for p in vis_pts]
            vs = [p[1] for p in vis_pts]
            if max(us) >= 0 and min(us) < cw and max(vs) >= 0 and min(vs) < ch:
                dist = float(np.hypot(xe, ye))
                cv2.putText(img, f"{dist:.0f}m",
                            (max(0, min(us)), max(12, min(vs) - 4)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.45, col, 1, cv2.LINE_AA)


_RIBBON_STATE = {"wps": None}


def draw_path_ribbon(img, ego_pred, K, Tce, cw, ch, W0=768, H0=432,
                     half_w=0.9, color=(60, 255, 120), alpha=0.38,
                     reset=False):
    """Project the predicted trajectory as a vehicle-width ground ribbon
    (filled, semi-transparent) into a camera image.

    Near a stop the ribbon FADES OUT with the predicted travel distance
    (no hard pop-off), and waypoints are EMA-smoothed across frames."""
    wps = np.concatenate([[[0.0, 0.0]], ego_pred[:12].reshape(6, 2)], 0)
    if not np.all(np.isfinite(wps)):
        # NaN frame (bad odometry upstream): draw nothing but DO NOT touch
        # the EMA state -- one bad frame must not poison every later frame
        return
    if (reset or _RIBBON_STATE["wps"] is None
            or not np.all(np.isfinite(_RIBBON_STATE["wps"]))):
        _RIBBON_STATE["wps"] = wps
    else:
        _RIBBON_STATE["wps"] = 0.55 * _RIBBON_STATE["wps"] + 0.45 * wps
    wps = _RIBBON_STATE["wps"].copy()
    trav = float(np.hypot(*(wps[-1] - wps[0])))
    # RETRACT instead of fade: the displayed ribbon length shrinks smoothly
    # with the predicted travel; the tip slides down toward the hood and
    # finally disappears under it (constant opacity throughout)
    s = min(max(trav / 3.0, 0.0), 1.0)
    disp_len = max(trav, 8.0 * s * s * (3 - 2 * s))
    if disp_len < 0.6:
        return
    # densify along the polyline
    seg = np.linalg.norm(np.diff(wps, axis=0), axis=1)
    t = np.concatenate([[0], np.cumsum(seg)])
    if t[-1] < disp_len:                 # extend along the last heading
        d = wps[-1] - wps[-3]
        d = d / max(np.linalg.norm(d), 1e-3)
        wps = np.concatenate([wps, [wps[-1] + d * (disp_len - t[-1])]], 0)
        seg = np.linalg.norm(np.diff(wps, axis=0), axis=1)
        t = np.concatenate([[0], np.cumsum(seg)])
    tt = np.linspace(0, min(t[-1], disp_len), 48)
    px = np.interp(tt, t, wps[:, 0])
    py = np.interp(tt, t, wps[:, 1])
    th = np.arctan2(np.gradient(py), np.gradient(px))
    lx, ly = px - half_w * np.sin(th), py + half_w * np.cos(th)
    rx, ry = px + half_w * np.sin(th), py - half_w * np.cos(th)
    sx, sy = cw / W0, ch / H0

    def proj(xs, ys):
        pts = np.stack([xs, ys, np.zeros_like(xs)], 1)
        pc = pts @ Tce[:3, :3].T + Tce[:3, 3]
        ok = pc[:, 2] > 0.3
        u = (K[0, 0] * pc[:, 0] / np.maximum(pc[:, 2], 0.3) + K[0, 2]) * sx
        v = (K[1, 1] * pc[:, 1] / np.maximum(pc[:, 2], 0.3) + K[1, 2]) * sy
        return np.stack([u, v], 1), ok

    L, okl = proj(lx, ly)
    R, okr = proj(rx, ry)
    ok = okl & okr
    if ok.sum() < 3:
        return
    L, R = L[ok], R[ok]
    poly = np.concatenate([L, R[::-1]], 0).astype(np.int32)
    poly[:, 0] = np.clip(poly[:, 0], -cw, 2 * cw)
    poly[:, 1] = np.clip(poly[:, 1], -ch, 2 * ch)
    ov = img.copy()
    cv2.fillPoly(ov, [poly.reshape(-1, 1, 2)], color)
    cv2.polylines(ov, [L.astype(np.int32).reshape(-1, 1, 2)], False, color, 2)
    cv2.polylines(ov, [R[::-1].astype(np.int32).reshape(-1, 1, 2)], False,
                  color, 2)
    img[:] = cv2.addWeighted(img, 1 - alpha, ov, alpha, 0)


DET2D_STRIDES = (4, 8, 16)


def decode_boxes2d_ms_np(hms, regs, thresh=0.3, topk=48):
    """Numpy port of DepthSegIPMNetV19.decode_boxes2d_ms, verified against the
    torch original on identical inputs. cv2.dilate stands in for max_pool2d."""
    out = None
    for si, (hm, reg) in enumerate(zip(hms, regs)):
        s = DET2D_STRIDES[si]
        p = 1.0 / (1.0 + np.exp(-np.clip(hm.astype(np.float32), -50, 50)))
        N, C, h, w = p.shape
        if out is None:
            out = [[] for _ in range(N)]
        k3 = np.ones((3, 3), np.uint8)
        for ni in range(N):
            pm = np.stack([cv2.dilate(p[ni, c], k3) for c in range(C)])
            pk = p[ni] * (pm == p[ni])
            flat = pk.reshape(-1)
            nkeep = min(topk, flat.size)
            idx = np.argpartition(-flat, nkeep - 1)[:nkeep]
            for j in idx:
                sc = float(flat[j])
                if sc <= thresh:
                    continue
                ccls, rc = int(j // (h * w)), int(j % (h * w))
                rr, cc = rc // w, rc % w
                o = reg[ni, :, rr, cc].astype(np.float32)
                out[ni].append((ccls, sc, (cc + float(o[1])) * s,
                                (rr + float(o[0])) * s,
                                float(np.exp(o[2])) * s,
                                float(np.exp(o[3])) * s))
    return out


def crop_bev_np(pred, xf_m, xr_m, view_f=60.0, view_r=60.0, yh_m=25.0):
    """Front view_f .. rear view_r crop of a row0=front BEV raster."""
    h, w = pred.shape[:2]
    res = (xf_m + xr_m) / h
    r0 = max(0, int((xf_m - view_f) / res))
    r1 = min(h, int((xf_m + view_r) / res))
    resw = 2 * 50.0 / w
    c0 = max(0, int((50.0 - yh_m) / resw))
    c1 = min(w, int((50.0 + yh_m) / resw))
    return pred[r0:r1, c0:c1]
